### ISSUE TITLE
updating indexes?

### ISSUE THREAD

**Issue by rjsorr** [JensUweUlrich/Taxor#13]
Hi, 

is it possible to update indexes/dbs without having to start from scratch? 

regards

**Comment by JensUweUlrich** [comment]
No, this is one of the main drawback of XOR filter data structures. They are unfortunately not updatable. You would need to go for tools implementing Bloom filters, like [ganon](https://github.com/pirovc/ganon) that support this feature for the cost of larger indexes and increased memory usage.
