### ISSUE TITLE
Issues downloading the GTDB-index

### ISSUE THREAD

**Issue by dalofa** [JensUweUlrich/Taxor#6]
Thanks a ton for writing taxor!

I am currently having problems downloading and using the GTDB hixf-index.

Downloading the GTDB-index file results in a MD5SUM of e24502ab2fe7c1edb415ee1f3141962c and using this index to run taxor search results in the process being killed. 

I have tried downloading the index using both the browser and wget. Is it possible to provide access to the index in another way? Do you have any other suggestions for approaching this problem?

As an aside, the refseq download have worked fine.

**Comment by JensUweUlrich** [comment]
Hi @dalofa

I'm actually building a new index for the latest GTDB release. It seems that there are some problems when downloading the index from my dropbox. I probably have to switch to amazon S3 for storing such large files. I will keep you updated asap when it's ready for download.

**Comment by JensUweUlrich** [comment]
Hi

I recently uploaded a new GTDB R220 index to Amazon S3. You can download it [here](https://taxor-idx.s3.amazonaws.com/gtdb_k22-s12.hixf). I hope this works now.

**Comment by JensUweUlrich** [comment]
Please re-open if the new index file did not resolve the problem
